### ISSUE TITLE
contribute for hacktoberfest

### ISSUE THREAD

**Issue by ayansiddiqui007** [ayansiddiqui007/hacktoberfest2022#1]

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

**Comment by ayansiddiqui007** [comment]
> Hey, I want to add program for live weather notifications in desktop. Can you please assign it to me?

Yes you can submit a pull request directly with your code if you want to contribute !

**Comment by ayansiddiqui007** [comment]
> Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

New pull request will be accepted for thee same add your code and do  new pull request.

**Comment by MSVelan** [comment]
@ayansiddiqui007 I have added the PR, it would be really helpful if you can merge this with the repo.
