### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by ayansiddiqui007** [ayansiddiqui007/hacktoberfest2022#3]
hacktoberfest

**Comment by ig77ayush** [comment]
This issue aligned to me

**Comment by Ankitrai2204** [comment]
Hello I want to contribute on this project. Can you please assign it to me and tell about our requirements.

**Comment by jatin41** [comment]
I want to contribute

**Comment by Jasiel-Stark8** [comment]
hey there i want to contribute

**Comment by HarshAggarwal1** [comment]
hi there, please allow me to contribute
