### ISSUE TITLE
can i create a simple BMI calculator using HTML ,CSS ,javascript

### ISSUE THREAD

**Issue by SajithMinrutha** [ayansiddiqui007/hacktoberfest2022#41]
please assign this to me under hacktoberfest2023

**Comment by TanushreeBorase** [comment]
I would like to work on this issue under Hacktoberfest2023 @SajithMinrutha

**Comment by ayansiddiqui007** [comment]
> I would like to work on this issue under Hacktoberfest2023 @ayansiddiqui007

Uh oh! You haven't made any pull/merge requests yet. Submit your first contribution to a participating project to get started with Hacktoberfest!

**Comment by ayansiddiqui007** [comment]
> please assign this to me under hacktoberfest2023

Uh oh! You haven't made any pull/merge requests yet. Submit your first contribution to a participating project to get started with Hacktoberfest!

**Comment by ayansiddiqui007** [comment]
Accepted, You can contribute more if you have remaining pull requests for hacktoberfest. Here i accept good first issue connects for the hacktoberfest
