### ISSUE TITLE
Morse Code Translator

### ISSUE THREAD

**Issue by ayansiddiqui007** [ayansiddiqui007/hacktoberfest2022#55]
Create a program that translates a string into Morse code.

**Comment by ayansiddiqui007** [comment]
> Can I attempt this?

Commit a new Pull Request i will accept as today is the last day of hacktoberfest so all the commits would be accepted today to help good coders come forward and motivate them at the same time

**Comment by SeaBebop** [comment]
Attempted this at https://github.com/ayansiddiqui007/hacktoberfest2022/pull/73
